version = 0.1

[default.deploy.parameters]
stack_name = "divergence-monitor-stack"
resolve_s3 = true
s3_prefix = "divergence-monitor-stack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ScheduleExpression=\"cron(0,15,30,45\""
image_repositories = []
